# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Auttapon Sae-na
title: Programmer
email: alche3rd@gmail.com
website:  https://github.com/alche3rd

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: user
github_username:  alche3rd
stackoverflow_username: "10943922"
# dribbble_username: user
# facebook_username: user
# flickr_username: user
# instagram_username: user
linkedin_username: alche3rd
# xing_username: user
# pinterest_username: user
# youtube_username: user
# googleplus_username: +user
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: About Me
  icon: fas fa-globe
  url: https://alche3rd.github.io/aboutme/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | 
  Experienced Software Developer with a strong background in API integration and data visualization. 
  Specialized in developing solutions using C#.NET and creating insightful data visualizations. 
  Proficient in resolving complex issues and optimizing software performance. 
  Achieved a significant reduction in redundant reporting time across the organization, enhancing overall productivity and efficiency.
  - Key Skills: .NET Developer, Coding Standards, Version Control, API Integration, Data Visualization, Front-end Frameworks.
  - Future Goals: Continuously improve my skills.
  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Electronic ENCON Fund Budgetary 
        sub_title: Programmer
        caption: 2018 - 2020
        #link: http://eefb.dede.go.th/eefb
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        description: |
          The Electronic ENCON Fund Budgetary is a web-based platform that provides budget management services for the Energy Conservation Fund under the Ministry of Energy. 
          The platform is designed to streamline and enhance the efficiency of budget-related processes, ensuring transparency and accountability in the allocation and utilization of funds.
        
      - layout: left
        title: Automotive Analysis Program
        sub_title: Devoloper
        caption: 2013
        quote: >
        description: |
          The Automotive Analysis Program is a traditional-style assistant tool designed to help users diagnose and identify the root causes of automotive issues. 
          The program interacts with users through a series of step-by-step questions to gather information and provide accurate analysis.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Krieng Thai Wattana
        link: https://www.ktw.co.th/
        # link_text: ktw.co.th
        sub_title: Programmer
        caption: 2020 - 2023
        quote: >
        description: | 
         - Developed middleware between internal API and external API using Blazor, Bootstrap, and C# .NET. 
         - Developed data visualizations using Google Data Studio for the marketing team to analyze and improve marketing strategies.
        

      - layout: left
        title: Giant System Design
        link: http://www.giantsystemdesign.com/
        # link_text: giantsystemdesign.com
        sub_title: Programmer
        caption: 2018 - 2020
        quote: >
        description: | 
         - Responsible for the maintenance and upgrade (MA) of the ILS System for the Royal Thai Navy’s Landing Platform Dock (LPD) - Singapore Technologies Marine (ST Marine).
         - Responsible for the maintenance and upgrade (MA) of the Electronic ENCON Fund Budgetary (EEFB) system for the Ministry of Energy, Department of Alternative Energy Development and Efficiency (DEDE).

      - layout: left
        title: VL & M Apparel
        sub_title: Network System Administrator
        caption: 2014 - 2016
        quote: >
        description: |
         - Responsible for the maintenance of the local network and Windows servers.
         - Troubleshot software, hardware, and databases.
        
      - layout: left
        title: Rod Suay Air and Sound
        sub_title: IT Support
        caption: 2010 - 2014
        quote: >
        description: | 
         - Responsible for the maintenance of the local network, supporting the specialized car tuning and diagnostic program.
         - Assisting users with tuning and diagnostic issues, and troubleshooting software and hardware.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Bansomdejchaopraya Rajabhat University
        caption: 2006 - 2013
        sub_title: BSc Computer Science
        quote: >
        description: |

      - layout: top-middle
        title: Taweethapisek School
        caption: 2003 - 2006
        sub_title: Science and Mathematics
        quote: >
        description: |

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Technical Skills
        description: |
          - C#
          - TypeScript
          - JavaScript
          - CLIPS (C Language Integrated Production System)
          - .NET
          - Bootstrap
          - Silverlight
          - CSS
          - XAML
          - JSON
          - XML
          - SQL
      - layout: left
        title: Database Management
        description: |
          - Microsoft SQL
          - Oracle 10G
          - MySQL
          - PostgreSQL
          - Microsoft Access
          - MariaDB
      - layout: left
        title: Tools & Applications
        description: |
          - Microsoft Visual Studio
          - Visual Studio Code
          - Docker
          - Git
          - JIRA
          - Google Data Studio
          - Power BI
          - TortoiseSVN
          - Microsoft Office
          - ABBYY
          - Alfresco
          - VMWare
      - layout: left
        title: Additional Skills
        description: |
          - Holds a personal car driver's license
          - 31 words per minute (Thai)
          - 33 words per minute (English)

  - title: A Little More About Me
    #layout: text
    # content: | # this will include new lines to allow paragraphs
    #   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #   - Gaming
    #   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #   Look at this cool image  
    #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming
      - Music
      - Manga & Anime
      - AI
      - Mechanic
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
